### ISSUE TITLE
Email notification feature when a news is submited in FE

### ISSUE THREAD

**Issue by kaolol** [kaystrobach/TYPO3.newssubmit#5]
Hi Key !
I didn't find anymore the email notification feature when a news is submited in FE
I took a look in the code, but I did'nt find it...

Is this feature still available ?

All the best,
Laurent

PS : If i may help in anyway, testing, translation in french, just ask !
Laurent

**Comment by frans-beech-it** [comment]
Hi Laurent,

yes this is still available see https://github.com/kaystrobach/TYPO3.newssubmit/blob/master/Classes/Controller/NewsController.php#L168

So setting:
plugin.tx_newssubmit.settings.recipientMail = you@domain.com 

should be enough to make it work.

gr. Frans

**Comment by kaolol** [comment]
Sorry, I've been really busy those days.
It work perfectly ! Great !
Thanks a lot !
I guess we can close this issue ;)
Have a nice day,
Laurent

**Comment by kaystrobach** [comment]
@kaolol please close issues you opened, once they are done in your opinion :smile:
