### ISSUE TITLE
french translation

### ISSUE THREAD

**Issue by kaystrobach** [kaystrobach/TYPO3.newssubmit#6]
@kaolol feel free to edit (even directly online) the following file https://github.com/kaystrobach/TYPO3.newssubmit/blob/master/Resources/Private/Language/locallang.xml to add french translation.

There is a nl example below the default section.

Thanks

**Comment by kaolol** [comment]
Translation : Done ! 
Pull request : Done !
;)
All the best
Laurent

**Comment by kaolol** [comment]
I guess we can close this issue if everything is ok for you,
All the best
Laurent

**Comment by kaystrobach** [comment]
yes we can :smile:
