### ISSUE TITLE
Show in preview is not cheked on news submited in frontend

### ISSUE THREAD

**Issue by kaolol** [kaystrobach/TYPO3.newssubmit#8]
Hi Kay
When a news is submitted in front-end, "Show in preview" is not cheked for image
If I understood good, it seems that it suppose to be the case 

./Classes/Property/TypeConverter/UploadedFileReferenceConverter.php:219:				'showinpreview' => 1,

Is it working for you ?
All the best,
Laurent

PS: as always, if I can help in anyway...

**Comment by fsaris** [comment]
Just tested, and indeed looks like it doesn't work.

gr. Frans

**Comment by WebPam** [comment]
It works !
This one is solved, but I looks like I cannot change the status myself !
