### ISSUE TITLE
Fill autheur and email field with logged feuser data

### ISSUE THREAD

**Issue by WebPam** [kaystrobach/TYPO3.newssubmit#9]
Hi,
Sorry, it's me again !

Use case
A user logged in frontend (feuser) publish a news in frontend with newssubmit.
Could be possible to fill automaticaly :
The field Author with his Name if available, otherwise login
The field Email with his email

Thank you again for this really cool EXT,
Be shure it will help for testing ! ;)
All the best
Laurent

**Comment by kaystrobach** [comment]
otherwise login can already be done with a login plugin on the page (just show not logged in) and the news plugin set to (just show to logged in)

The author thingy is discussable, but imho possible

**Comment by WebPam** [comment]
Hey ! What a fast reply !
Thank's a lot !

Yes, I mean, in my case, the user is already logged.
Just want to find a way to get name and email of the feuser posting news in frontend automaticaly passed to the news record

**Comment by kaystrobach** [comment]
@fsaris basicly you already did it ;)

https://github.com/kaystrobach/TYPO3.newssubmit/blob/master/Classes/Controller/NewsController.php#L127

But the newAction normally does not get an News Attribute, to fix that I would suggest to create a new News if no News is given via the attributes ... any objections?

**Comment by WebPam** [comment]
Hi Kay, Hi Frans,
I am so sorry that I cannot help much as I am just a poor integrator, only able to put together what  coding genius create ;) 
But by the time I am learning more and more, and this piece of code looks good to me !
As always, I will be there for testing, bug reports is the best I do, together with features request to make your work even better ;)
Thanks so much for your help,
Good evening, I have to go, but i'll  de back  tomorrow
All the best,
Laurent

**Comment by beechit** [comment]
The author and email address are currently already prefilled when logged in. I'm currently using this in one of my projects.

@kaystrobach if no News param is given it is NULL, so the check you linked to creates a new News object and fills the author and email property.

**Comment by fsaris** [comment]
The author and email address are currently already prefilled when logged in. I'm currently using this in one of my projects.

@kaystrobach if no News param is given it is NULL, so the check you linked to creates a new News object and fills the author and email property.

**Comment by kaystrobach** [comment]
Mhmm, maybe to tired to get it, will check tomorrow.
Maybe we should do a New TER release ;)

----- Originale Nachricht -----
Von: "Beech.it" <notifications@github.com>
Gesendet: 30.07.2015 - 21:58
An: "kaystrobach/TYPO3.newssubmit" <TYPO3.newssubmit@noreply.github.com>
Betreff: Re: [TYPO3.newssubmit] Fill autheur and email field with logged feuser data (#9)

**Comment by kaystrobach** [comment]
@WebPam can you please recheck with the current master https://github.com/kaystrobach/TYPO3.newssubmit/archive/master.zip just download and extract the zip file and then replace the extension files with the ones from the zip

**Comment by WebPam** [comment]
Indeed, everything for fine ! 
Almost ;)
https://github.com/kaystrobach/TYPO3.newssubmit/pull/10
So cool !
Thank's a lot
